---
title: "The role of community participation and social engagement in the prevention and control of dengue fever in Dhaka City"
author: "Md. Jubayer Hossain"
format: html
editor: visual
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(tidyr)
library(stringr)
library(janitor)
library(gtsummary)
library(readxl)
library(flextable)
library(officer)
```

```{r}
data <- read_excel("data/dengue_community_cleaned.xlsx")
head(data)
```

```{r}
# Table 1: Demographic characteristics 
table1 <- data %>% 
  select(1:4) %>% 
  tbl_summary(missing = "no", 
              type = everything() ~ "categorical") %>% 
  as_flex_table() %>% 
  set_table_properties(width = 1, layout = "autofit")

table1
# Export table 1 
# save_as_docx(table1, path = "tables/Table1.docx") 
```

```{r}
# Clean colnames 
info_source_raw <- data %>% 
  clean_names()

# List all the responses  
fixed_responses <- c("Television", "Radio", "Newspaper", "Friends/Neighbors","Hospital","Health workers")

# Seperate rows by delimeter 
info_source_tidy <- info_source_raw %>% 
 separate_rows(source_of_dengue_related_information, 
                sep = ", ") %>% 
 mutate(source_of_dengue_related_information = case_when(
    source_of_dengue_related_information %in% fixed_responses ~ source_of_dengue_related_information,
    TRUE ~ "Others"
  ))

# Count the responses 
info_source_tidy %>% 
  count(source_of_dengue_related_information)
```

```{r}
# Table 2: Perception to control  dengue through community participation
table2 <- data %>% 
  select(13:20) %>% 
  tbl_summary(missing = "no", 
              type = everything() ~ "categorical") %>% 
  as_flex_table() %>% 
  set_table_properties(width = 1, layout = "autofit")

table2
# Export table 2 
# save_as_docx(table1, path = "tables/Table1.docx") 
```

```{r}
# Table 3:  Association between community participation and dengue control practices
table3 <- data %>% 
  select(21:30) %>% 
  tbl_summary(missing = "no", 
              type = everything() ~ "categorical") %>% 
  as_flex_table() %>% 
  set_table_properties(width = 1, layout = "autofit")

table3
# Export table 3 
# save_as_docx(table1, path = "tables/Table1.docx") 
```
